import type {
  AppNotification,
  AppState,
  Member,
  Transaction,
} from './types'
import type { Action } from './actions'
import { authorize, declineReasonForUser, remainingLimit } from './engine'
import { rootScreen } from './policy'
import { SCHEMA_VERSION, seedState } from './seed'
import { money } from '../lib/format'

/**
 * All state transitions for the prototype.
 *
 * The reducer is pure: ids and timestamps are generated by the action creators
 * in actions.ts and passed in as payload, so a given (state, action) pair
 * always produces the same next state.
 */

const patchMember = (
  state: AppState,
  id: string,
  fn: (m: Member) => Member,
): Member[] => state.members.map((m) => (m.id === id ? fn(m) : m))

const pushNotification = (
  state: AppState,
  notification: AppNotification,
): AppNotification[] => [notification, ...state.notifications].slice(0, 20)

export function reducer(state: AppState, action: Action): AppState {
  switch (action.type) {
    case 'SET_MODE': {
      let next = { ...state, mode: action.mode }

      /**
       * Entering the onboarding mode should land on the invitation itself, not
       * on a chooser. Auto-select the most recently sent pending invite unless
       * a specific one is already in flight (set by "Open X's invite" in the
       * User app, which targets a member explicitly).
       *
       * The picker is still the fallback when nothing is pending — otherwise
       * the mode would be a dead end.
       */
      if (action.mode === 'onboarding') {
        const inFlight = next.members.find(
          (m) => m.id === next.onboarding.memberId && m.status !== 'removed',
        )
        if (!inFlight) {
          const target = next.members
            .filter((m) => m.status === 'pending')
            .sort(
              (a, b) =>
                new Date(b.invite.sentAt).getTime() -
                new Date(a.invite.sentAt).getTime(),
            )[0]
          next = {
            ...next,
            onboarding: { memberId: target?.id ?? null, step: 0 },
          }
        }
      }

      return { ...next, stack: [rootScreen(action.mode, next)] }
    }

    case 'NAV_PUSH':
      return { ...state, stack: [...state.stack, action.screen] }

    case 'NAV_POP':
      return {
        ...state,
        stack:
          state.stack.length > 1 ? state.stack.slice(0, -1) : state.stack,
      }

    case 'NAV_RESET':
      return { ...state, stack: [action.screen] }

    case 'RESET_DEMO': {
      const fresh = seedState()
      return { ...fresh, mode: 'select' }
    }

    /**
     * Seed state always has a card on the account, so the Family Hub empty
     * state would otherwise be unreachable. This clears the members while
     * keeping the User's own account intact.
     */
    case 'RESET_EMPTY': {
      const fresh = seedState()
      return {
        ...fresh,
        mode: 'user',
        stack: [{ name: 'family-hub' }],
        members: [],
        transactions: fresh.transactions.filter((t) => t.cardId === 'user'),
        consents: [],
        notifications: [],
      }
    }

    case 'SET_BALANCE':
      return {
        ...state,
        account: { ...state.account, balance: action.balance },
      }

    // ---------------------------------------------------------------- members

    case 'ADD_MEMBER':
      return {
        ...state,
        members: [...state.members, action.member],
        consents: [...state.consents, ...action.consents],
      }

    case 'PATCH_MEMBER':
      return {
        ...state,
        members: patchMember(state, action.id, (m) => ({ ...m, ...action.patch })),
      }

    case 'PATCH_CONTROLS':
      return {
        ...state,
        members: patchMember(state, action.id, (m) => ({
          ...m,
          controls: { ...m.controls, ...action.patch },
        })),
      }

    case 'SET_LIMIT':
      return {
        ...state,
        members: patchMember(state, action.id, (m) => ({
          ...m,
          monthlyLimit: action.monthlyLimit,
          refresh: { cadence: action.cadence, nextAt: action.nextAt },
          // A limit change never retroactively clears recorded spend.
          refreshConstrainedAt:
            action.monthlyLimit !== null &&
            state.account.balance < action.monthlyLimit
              ? m.refreshConstrainedAt
              : null,
        })),
      }

    case 'ONE_OFF_INCREASE':
      return {
        ...state,
        members: patchMember(state, action.id, (m) => ({
          ...m,
          monthlyLimit:
            m.monthlyLimit === null ? null : m.monthlyLimit + action.amount,
        })),
      }

    case 'SET_NOTIF_PREFS':
      return {
        ...state,
        members: patchMember(state, action.id, (m) => ({
          ...m,
          notifications: { ...m.notifications, ...action.patch },
        })),
      }

    case 'FREEZE': {
      const member = state.members.find((m) => m.id === action.id)
      if (!member) return state
      const byMember = action.source === 'member'
      return {
        ...state,
        members: patchMember(state, action.id, (m) => ({
          ...m,
          status: 'frozen',
          freezeSource: action.source,
        })),
        // Freeze events sit in the mandatory alert group — always notified.
        notifications: pushNotification(state, {
          id: action.notificationId,
          kind: 'freeze',
          memberId: action.id,
          transactionId: null,
          at: action.at,
          read: false,
          title: byMember
            ? `${member.name} froze their card`
            : `${member.name}'s card is frozen`,
          body: byMember
            ? `${member.name} froze their own Family Hub card. They can unfreeze it themselves.`
            : `You froze this card. Only you can unfreeze it.`,
        }),
      }
    }

    case 'UNFREEZE':
      return {
        ...state,
        members: patchMember(state, action.id, (m) => ({
          ...m,
          status: 'active',
          freezeSource: null,
        })),
      }

    case 'REMOVE_MEMBER':
      return {
        ...state,
        members: patchMember(state, action.id, (m) => ({
          ...m,
          status: 'removed',
          freezeSource: null,
          removalRequestedAt: null,
        })),
        notifications: state.notifications.filter(
          (n) => n.memberId !== action.id,
        ),
      }

    case 'REQUEST_REMOVAL': {
      const member = state.members.find((m) => m.id === action.id)
      if (!member) return state
      return {
        ...state,
        members: patchMember(state, action.id, (m) => ({
          ...m,
          removalRequestedAt: action.at,
        })),
        notifications: pushNotification(state, {
          id: action.notificationId,
          kind: 'freeze',
          memberId: action.id,
          transactionId: null,
          at: action.at,
          read: false,
          title: `${member.name} asked to give up their card`,
          body: `${member.name} has asked for their Family Hub card to be removed. You need to confirm before it stops working.`,
        }),
      }
    }

    case 'CANCEL_REMOVAL_REQUEST':
      return {
        ...state,
        members: patchMember(state, action.id, (m) => ({
          ...m,
          removalRequestedAt: null,
        })),
      }

    case 'ADD_CONSENT':
      return { ...state, consents: [...state.consents, action.record] }

    // ------------------------------------------------------------ onboarding

    case 'ONBOARDING_START':
      return {
        ...state,
        onboarding: { memberId: action.memberId, step: 0 },
        stack: [{ name: 'onboarding' }],
      }

    case 'ONBOARDING_EXIT':
      return {
        ...state,
        onboarding: { memberId: null, step: 0 },
        stack: [{ name: 'invite-picker' }],
      }

    case 'ONBOARDING_STEP':
      return {
        ...state,
        onboarding: { ...state.onboarding, step: action.step },
      }

    case 'ONBOARDING_PATCH_MEMBER': {
      const id = state.onboarding.memberId
      if (!id) return state
      return {
        ...state,
        members: patchMember(state, id, (m) => ({ ...m, ...action.patch })),
      }
    }

    case 'ONBOARDING_COMPLETE': {
      const id = state.onboarding.memberId
      if (!id) return state
      return {
        ...state,
        members: patchMember(state, id, (m) => ({
          ...m,
          status: 'active',
          invite: { ...m.invite, acceptedAt: action.at },
        })),
      }
    }

    // ----------------------------------------------------------- transactions

    case 'ATTEMPT_TRANSACTION': {
      const { candidate, notificationId } = action
      const member = state.members.find((m) => m.id === candidate.cardId)
      if (!member) return state

      const result = authorize({
        amount: candidate.amount,
        channel: candidate.channel,
        category: candidate.category,
        member,
        balance: state.account.balance,
      })

      if (result.approved) {
        const txn: Transaction = { ...candidate, status: 'approved' }
        const notify = member.notifications.spendAlerts
        return {
          ...state,
          transactions: [txn, ...state.transactions],
          account: {
            ...state.account,
            balance: Number(
              (state.account.balance - candidate.amount).toFixed(2),
            ),
          },
          members: patchMember(state, member.id, (m) => ({
            ...m,
            periodSpend: Number((m.periodSpend + candidate.amount).toFixed(2)),
          })),
          notifications: notify
            ? pushNotification(state, {
                id: notificationId,
                kind: 'spend',
                memberId: member.id,
                transactionId: candidate.id,
                at: candidate.at,
                read: false,
                title: `${member.name} spent ${money(candidate.amount)}`,
                body: `${candidate.merchant} · ${
                  member.notifications.delivery === 'daily'
                    ? 'included in your daily summary'
                    : 'card ending ' + member.card.last4
                }`,
              })
            : state.notifications,
        }
      }

      const txn: Transaction = {
        ...candidate,
        status: 'declined',
        decline: { rule: result.rule, limitValue: result.limitValue },
      }

      return {
        ...state,
        transactions: [txn, ...state.transactions],
        // Declines are in the mandatory alert group — always notified.
        notifications: pushNotification(state, {
          id: notificationId,
          kind: 'decline',
          memberId: member.id,
          transactionId: candidate.id,
          at: candidate.at,
          read: false,
          title: `${member.name}'s card was declined at ${candidate.merchant}`,
          body: `${money(candidate.amount)} ${declineReasonForUser(txn, member)}`,
        }),
      }
    }

    // --------------------------------------------------------------- refresh

    case 'RUN_REFRESH': {
      const member = state.members.find((m) => m.id === action.id)
      if (!member || member.monthlyLimit === null) return state

      const constrained = state.account.balance < member.monthlyLimit

      return {
        ...state,
        members: patchMember(state, action.id, (m) => ({
          ...m,
          periodSpend: 0,
          periodStart: action.at,
          periodEnd: action.periodEnd,
          refresh: { ...m.refresh, nextAt: action.nextAt },
          refreshConstrainedAt: constrained ? action.at : null,
        })),
        notifications: pushNotification(state, {
          id: action.notificationId,
          kind: constrained ? 'refresh_failed' : 'spend',
          memberId: action.id,
          transactionId: null,
          at: action.at,
          read: false,
          title: constrained
            ? `${member.name}'s budget refreshed, but funds are short`
            : `${member.name}'s budget refreshed`,
          body: constrained
            ? `The card spending limit reset to ${money(
                member.monthlyLimit,
              )}, but your account currently holds ${money(
                state.account.balance,
              )}. The card can only authorise up to available funds.`
            : `The card spending limit reset to ${money(member.monthlyLimit)} for the new period.`,
        }),
      }
    }

    // --------------------------------------------------------- notifications

    case 'READ_NOTIFICATION':
      return {
        ...state,
        notifications: state.notifications.map((n) =>
          n.id === action.id ? { ...n, read: true } : n,
        ),
      }

    case 'DISMISS_NOTIFICATION':
      return {
        ...state,
        notifications: state.notifications.filter((n) => n.id !== action.id),
      }

    case 'CLEAR_MEMBER_NOTIFICATIONS':
      return {
        ...state,
        notifications: state.notifications.filter(
          (n) => !(n.memberId === action.id && n.kind === action.kind),
        ),
      }

    default:
      return state
  }
}

/** Rehydrates persisted state, discarding anything from an older schema. */
export function hydrate(raw: string | null): AppState {
  if (!raw) return seedState()
  try {
    const parsed = JSON.parse(raw) as AppState
    if (parsed?.schema !== SCHEMA_VERSION) return seedState()
    // Land on the mode selector on reload so the demo always has an entry point.
    return { ...parsed, mode: parsed.mode ?? 'select' }
  } catch {
    return seedState()
  }
}

/** Convenience for screens that need to show headroom without importing engine. */
export const headroom = remainingLimit
